### ISSUE TITLE
Dependencies don't work for expo build IOS

### ISSUE THREAD

**Issue by hraschan** [mahevstark/fiction-expo-restart#1]
You are using [@unimodules/core and  @unimodules/react-native-adapter as a dependency. Those two packages cant get build by expo eas build for IOS. It causes the build to crash.

https://github.com/expo/expo/issues/15648

In the above Github Issue you can see that every dependency which contains @unimodules needs to be removed in order to perform a ios build

**Comment by fatima2027** [comment]
Yes, got the same error!

**Comment by tlmader** [comment]
Same error as well :)

I just replaced my usage with `Updates.reloadAsync();`.

**Comment by hassanAwanAlvi** [comment]
Same error. I had to remove this library in order for my project to build...

I wrote a separate function 

`expo install expo-updates
`
```
import * as Updates from 'expo-updates';
const Restart = ()=>{
    if(Platform.OS=="web")
    {
        window.location.reload()
    }
    else{
        Updates.reloadAsync();
    }
}

```
and used this function for restart.

**Comment by mahevstark** [comment]
Those dependencies are removed now. Please try version 1.1.3
